version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/terraform" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/ui" # Location of package manifests
    schedule:
      interval: "weekly"
