/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.4.1/userguide/multi_project_builds.html
 */

rootProject.name = "theagainagain"

val gprUsername = extra.has("gpr.user").let { if (it) extra.get("gpr.user") as String else System.getenv("USERNAME") as String}
val gprToken = extra.has("gpr.key").let { if (it) extra.get("gpr.key") as String else System.getenv("GITHUB_TOKEN") as String}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            url = uri("https://jitpack.io")
        }
        maven {
            url = uri("https://maven.pkg.github.com/whodevil/jvm-platform")
            credentials {
                username = gprUsername
                password = gprToken
            }
        }
        maven { url = uri("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven") }
    }

    versionCatalogs {
        create("libs") {
            from("info.offthecob.jvm.platform:catalog:v0.0.12")
        }
    }
}