on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    outputs:
      repo: ${{ jobs.build.outputs.repo }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{steps.image.outputs.id}}
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - run: aws ecr create-repository --repository-name ${github.repository} || true
      - run: echo "::set-output name=id::${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}"
        id: image
