name: 'Deploy'
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ui:
    uses: "./.github/workflows/UI.yml"
  staging-plan:
    uses: ./.github/workflows/tf-plan.yml
    needs: [ ui ]
    with:
      environment: staging
      uiArtifactName: ${{ needs.ui.outputs.archive }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
  staging-apply:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/tf-apply.yml
    needs: [ staging-plan, ui ]
    with:
      environment: staging
      uiArtifactName: ${{ needs.ui.outputs.archive }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  production-plan:
    uses: ./.github/workflows/tf-plan.yml
    needs: [ ui ]
    with:
      environment: production
      uiArtifactName: ${{ needs.ui.outputs.archive }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
  production-apply:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/tf-apply.yml
    needs: [ production-plan, ui ]
    with:
      environment: production
      uiArtifactName: ${{ needs.ui.outputs.archive }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
