name: 'Deploy'
on:
  push:
    branches:
      - master
jobs:
  ui:
    uses: "./.github/workflows/UI.yml"
  jvm:
    uses: "./.github/workflows/JVM.yml"
    needs: [createEcr]
    with:
      repo: ${{ needs.createEcr.outputs.repo }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  imageSyncStaging:
    needs: [ jvm ]
    uses: ./.github/workflows/image-sync.yml
    with:
      environment: staging
      tag: ${{ needs.jvm.outputs.tag }}
      image: ${{ needs.jvm.outputs.image }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  staging:
    uses: ./.github/workflows/terraform.yml
    needs: [ui, imageSyncStaging]
    with:
      apply: true
      environment: staging
      uiArtifactName: ${{ needs.ui.outputs.archive }}
      image: ${{ needs.imageSyncStaging.outputs.repo }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
