name: 'Deploy'
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ui:
    uses: "./.github/workflows/UI.yml"
  jvm:
    uses: "./.github/workflows/JVM.yml"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  staging-plan:
    uses: ./.github/workflows/tf-plan.yml
    needs: [ ui, jvm ]
    with:
      environment: staging
      uiArtifactName: ${{ needs.ui.outputs.archive }}
      tag: ${{ needs.jvm.outputs.tag }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
  staging-apply:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/tf-apply.yml
    needs: [ staging-plan, ui ]
    with:
      environment: staging
      uiArtifactName: ${{ needs.ui.outputs.archive }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
  production-plan:
    uses: ./.github/workflows/tf-plan.yml
    needs: [ ui, jvm ]
    with:
      environment: production
      uiArtifactName: ${{ needs.ui.outputs.archive }}
      tag: ${{ needs.jvm.outputs.tag }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
  production-apply:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/tf-apply.yml
    needs: [ production-plan, ui ]
    with:
      environment: production
      uiArtifactName: ${{ needs.ui.outputs.archive }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
