name: 'Deploy'
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ui:
    uses: "./.github/workflows/UI.yml"
  jvm:
    uses: "./.github/workflows/JVM.yml"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  staging:
    uses: ./.github/workflows/terraform.yml
    needs: [ui, jvm]
    with:
      apply: ${{ github.event_name != 'pull_request' }}
      environment: staging
      uiArtifactName: ${{ needs.ui.outputs.archive }}
      tag: ${{ needs.jvm.outputs.tag }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
  production:
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/terraform.yml
    needs: [ ui, jvm, staging ]
    with:
      apply: ${{ github.event_name != 'pull_request' }}
      environment: production
      uiArtifactName: ${{ needs.ui.outputs.archive }}
      tag: ${{ needs.jvm.outputs.tag }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ZONE_ID: ${{ secrets.ZONE_ID }}
