name: PR Builder
on:
  - pull_request
jobs:
  ui:
    uses: "./.github/workflows/UI.yml"
  jib:
    uses: "./.github/workflows/JVM.yml"
    with:
      registry: ghcr.io
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      apply: false
      environment: staging
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}