name: PR Builder
on:
  - pull_request
jobs:
  createEcr:
    uses: ./.github/workflows/create-ecr.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ui:
    uses: "./.github/workflows/UI.yml"
  jvm:
    needs: [createEcr]
    uses: "./.github/workflows/JVM.yml"
    with:
      repo: ${{ needs.createEcr.outputs.repo }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  staging:
    needs: [ui, jvm]
    uses: ./.github/workflows/terraform.yml
    with:
      apply: false
      environment: staging
      uiArtifactName: ${{ needs.ui.outputs.archive }}
      image: ${{ needs.ui.outputs.image }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}