name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish UI Builder to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: whodevil/ui-builder
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ui-builder.Dockerfile