name: "Terraform"
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      environment:
        required: true
        type: string
      apply:
        required: true
        type: boolean
      uiArtifactName:
        required: true
        type: string
      registry:
        required: true
        type: string
      tag:
        required: true
        type: string
jobs:
  terraform:
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'
      TF_VAR_DOMAIN_NAME: ${{ secrets.TF_VAR_DOMAIN_NAME }}
      TF_VAR_API_IMAGE: ${{ inputs.registry }}/${{ github.repository }}-${{ inputs.environment }}:${{ inputs.tag }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.uiArtifactName }}
          path: terraform/
      - run: tar -xzf ${{ inputs.uiArtifactName }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0
      - run: terraform fmt
      - run: terraform init
      - run: terraform validate
      - run: terraform workspace select ${{ inputs.environment }}
      - run: terraform plan -out=.tfPlan
      - run: terraform apply -auto-approve .tfPlan
        if: inputs.apply == true
