name: "Terraform"
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      environment:
        required: true
        type: string
      apply:
        required: true
        type: boolean
      uiArtifactName:
        required: true
        type: string
      image:
        required: true
        type: string
jobs:
  terraform:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.uiArtifactName }}
          path: terraform/
      - run: tar -xzvf ${{ inputs.uiArtifactName }}
      - run: ls -l build
      - run: |
          sudo apt-get update
          sudo apt-get -y install skopeo
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0
      - run: terraform fmt
      - run: terraform init
      - run: terraform validate
      - run: terraform workspace select ${{ inputs.environment }}
      - run: terraform plan
      - run: terraform apply -auto-approve
        if: inputs.apply == true
