name: "OpenTofu Apply"
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DISTRIBUTION_ID:
        required: true
    inputs:
      environment:
        required: true
        type: string
      uiArtifactName:
        required: true
        type: string
jobs:
  tfApply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-west-2'
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - run: pip install awscli
      - uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.uiArtifactName }}
          path: terraform/
      - run: tar xzf ${{ inputs.uiArtifactName }}
      - uses: actions/download-artifact@v7
        with:
          name: tfPlan-${{ inputs.environment }}
          path: terraform/
      - uses: opentofu/setup-opentofu@v2
        with:
          tofu_version: "1.11.7"
      - name: tofu apply
        run: |
          tofu fmt
          tofu init
          tofu validate
          tofu workspace select ${{ inputs.environment }}
          tofu apply -auto-approve tfPlan
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths '/*'
