name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://ubuntu:latest
    - name: install pre-reqs
      run: |
        apt-get update
        apt-get install python python-pip npm yarn -y
        pip install awscli
    - name: ls
      run: ls
