name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: 'install pre-reqs'
      run: |
        sudo apt-get update
        sudo apt-get install python python-pip npm yarn -y
        sudo pip install awscli
    - name: 'yarn build'
      run: cd ui && yarn build
