name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: install pre-reqs
      run: |
        sudo apt-get update
        sudo apt-get install python python-pip npm yarn -y
        sudo pip install awscli
    - name: yarn install
      run: cd ui && yarn install
    - name: yarn build
      run: cd ui && yarn build
    - name: archive name
      run: echo "##[set-output name=name;]$(echo build/theagainagain-${GITHUB_REF#refs/heads/}.tar.gz)"
      id: archive_name
    - name: tar ui
      run: mkdir build && tar -czvf ${{steps.archive_name.outputs.name}} ui/build
