name: "UI Build"
on:
  workflow_call:
    outputs:
      archive:
        description: "a tar.gz of the UI artifact uploaded to github artifacts repo"
        value: ${{ jobs.ui.outputs.archive }}
jobs:
  ui:
    name: 'Publish UI'
    runs-on: ubuntu-latest
    outputs:
      archive: ${{steps.archive_name.outputs.name}}
    steps:
      - uses: actions/checkout@v1
      - name: install pre-reqs
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip npm yarn -y
          sudo pip install awscli
      - name: yarn install
        run: cd ui && yarn install
      - name: yarn build
        run: cd ui && yarn build
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: archive name
        run: echo "##[set-output name=name;]$(echo theagainagain-${{ steps.vars.outputs.sha_short }}.tar.gz)"
        id: archive_name
      - name: branch name
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
        id: branch_name
      - name: tar ui
        run: mkdir build && tar -czvf build/${{steps.archive_name.outputs.name}} ui/build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{steps.archive_name.outputs.name}}
          path: build/${{steps.archive_name.outputs.name}}