name: "UI"
on:
  workflow_call:
    outputs:
      archive:
        description: "a tar.gz of the UI artifact uploaded to github artifacts repo"
        value: ${{ jobs.build.outputs.archive }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      archive: ${{steps.archive_name.outputs.name}}
    defaults:
      run:
        working-directory: ui
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - id: archive_name
        run: echo "##[set-output name=name;]$(echo theagainagain-${{ steps.vars.outputs.sha_short }}.tar.gz)"
      - run: tar -czvf ${{steps.archive_name.outputs.name}} ./build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{steps.archive_name.outputs.name}}
          path: ui/${{steps.archive_name.outputs.name}}