name: "UI"
on:
  workflow_call:
    outputs:
      archive:
        description: "a tar.gz of the UI artifact uploaded to github artifacts repo"
        value: ${{ jobs.build.outputs.archive }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      archive: ${{steps.archive_name.outputs.name}}
    defaults:
      run:
        working-directory: ui
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.107.0'
          extended: true
      - name: Build
        run: hugo --minify
      - id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - id: archive_name
        run: echo "name=$(echo theagainagain-${{ steps.vars.outputs.sha_short }}.tar.gz)" >> $GITHUB_OUTPUT
      - run: tar -czvf ${{steps.archive_name.outputs.name}} ./public
      - uses: actions/upload-artifact@v4
        with:
          name: ${{steps.archive_name.outputs.name}}
          path: ui/${{steps.archive_name.outputs.name}}
